// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/museum/anchor.proto

package omo_msp_museum

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AnchorInfo struct {
	Uid                  string        `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64        `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64         `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64         `protobuf:"varint,4,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string        `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string        `protobuf:"bytes,6,opt,name=operator,proto3" json:"operator,omitempty"`
	Name                 string        `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string        `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	Cover                string        `protobuf:"bytes,9,opt,name=cover,proto3" json:"cover,omitempty"`
	Parent               string        `protobuf:"bytes,10,opt,name=parent,proto3" json:"parent,omitempty"`
	Panorama             string        `protobuf:"bytes,11,opt,name=panorama,proto3" json:"panorama,omitempty"`
	Link                 string        `protobuf:"bytes,12,opt,name=link,proto3" json:"link,omitempty"`
	Owner                string        `protobuf:"bytes,13,opt,name=owner,proto3" json:"owner,omitempty"`
	Position             *PositionInfo `protobuf:"bytes,14,opt,name=position,proto3" json:"position,omitempty"`
	Tags                 []string      `protobuf:"bytes,15,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AnchorInfo) Reset()         { *m = AnchorInfo{} }
func (m *AnchorInfo) String() string { return proto.CompactTextString(m) }
func (*AnchorInfo) ProtoMessage()    {}
func (*AnchorInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f070abf93908957a, []int{0}
}

func (m *AnchorInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnchorInfo.Unmarshal(m, b)
}
func (m *AnchorInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnchorInfo.Marshal(b, m, deterministic)
}
func (m *AnchorInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnchorInfo.Merge(m, src)
}
func (m *AnchorInfo) XXX_Size() int {
	return xxx_messageInfo_AnchorInfo.Size(m)
}
func (m *AnchorInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AnchorInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AnchorInfo proto.InternalMessageInfo

func (m *AnchorInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *AnchorInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AnchorInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *AnchorInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *AnchorInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *AnchorInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *AnchorInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AnchorInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *AnchorInfo) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *AnchorInfo) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *AnchorInfo) GetPanorama() string {
	if m != nil {
		return m.Panorama
	}
	return ""
}

func (m *AnchorInfo) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *AnchorInfo) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *AnchorInfo) GetPosition() *PositionInfo {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *AnchorInfo) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ReqAnchorAdd struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Parent               string   `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Owner                string   `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Operator             string   `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Tags                 []string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqAnchorAdd) Reset()         { *m = ReqAnchorAdd{} }
func (m *ReqAnchorAdd) String() string { return proto.CompactTextString(m) }
func (*ReqAnchorAdd) ProtoMessage()    {}
func (*ReqAnchorAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_f070abf93908957a, []int{1}
}

func (m *ReqAnchorAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqAnchorAdd.Unmarshal(m, b)
}
func (m *ReqAnchorAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqAnchorAdd.Marshal(b, m, deterministic)
}
func (m *ReqAnchorAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqAnchorAdd.Merge(m, src)
}
func (m *ReqAnchorAdd) XXX_Size() int {
	return xxx_messageInfo_ReqAnchorAdd.Size(m)
}
func (m *ReqAnchorAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqAnchorAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqAnchorAdd proto.InternalMessageInfo

func (m *ReqAnchorAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqAnchorAdd) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *ReqAnchorAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqAnchorAdd) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqAnchorAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqAnchorAdd) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ReqAnchorUpdate struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Operator             string   `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqAnchorUpdate) Reset()         { *m = ReqAnchorUpdate{} }
func (m *ReqAnchorUpdate) String() string { return proto.CompactTextString(m) }
func (*ReqAnchorUpdate) ProtoMessage()    {}
func (*ReqAnchorUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_f070abf93908957a, []int{2}
}

func (m *ReqAnchorUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqAnchorUpdate.Unmarshal(m, b)
}
func (m *ReqAnchorUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqAnchorUpdate.Marshal(b, m, deterministic)
}
func (m *ReqAnchorUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqAnchorUpdate.Merge(m, src)
}
func (m *ReqAnchorUpdate) XXX_Size() int {
	return xxx_messageInfo_ReqAnchorUpdate.Size(m)
}
func (m *ReqAnchorUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqAnchorUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqAnchorUpdate proto.InternalMessageInfo

func (m *ReqAnchorUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqAnchorUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqAnchorUpdate) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqAnchorUpdate) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type ReplyAnchorOne struct {
	Info                 *AnchorInfo  `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyAnchorOne) Reset()         { *m = ReplyAnchorOne{} }
func (m *ReplyAnchorOne) String() string { return proto.CompactTextString(m) }
func (*ReplyAnchorOne) ProtoMessage()    {}
func (*ReplyAnchorOne) Descriptor() ([]byte, []int) {
	return fileDescriptor_f070abf93908957a, []int{3}
}

func (m *ReplyAnchorOne) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyAnchorOne.Unmarshal(m, b)
}
func (m *ReplyAnchorOne) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyAnchorOne.Marshal(b, m, deterministic)
}
func (m *ReplyAnchorOne) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyAnchorOne.Merge(m, src)
}
func (m *ReplyAnchorOne) XXX_Size() int {
	return xxx_messageInfo_ReplyAnchorOne.Size(m)
}
func (m *ReplyAnchorOne) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyAnchorOne.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyAnchorOne proto.InternalMessageInfo

func (m *ReplyAnchorOne) GetInfo() *AnchorInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReplyAnchorOne) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReplyAnchorList struct {
	Total                uint32        `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	PageMax              uint32        `protobuf:"varint,2,opt,name=pageMax,proto3" json:"pageMax,omitempty"`
	PageNow              uint32        `protobuf:"varint,3,opt,name=pageNow,proto3" json:"pageNow,omitempty"`
	List                 []*AnchorInfo `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`
	Status               *ReplyStatus  `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReplyAnchorList) Reset()         { *m = ReplyAnchorList{} }
func (m *ReplyAnchorList) String() string { return proto.CompactTextString(m) }
func (*ReplyAnchorList) ProtoMessage()    {}
func (*ReplyAnchorList) Descriptor() ([]byte, []int) {
	return fileDescriptor_f070abf93908957a, []int{4}
}

func (m *ReplyAnchorList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyAnchorList.Unmarshal(m, b)
}
func (m *ReplyAnchorList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyAnchorList.Marshal(b, m, deterministic)
}
func (m *ReplyAnchorList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyAnchorList.Merge(m, src)
}
func (m *ReplyAnchorList) XXX_Size() int {
	return xxx_messageInfo_ReplyAnchorList.Size(m)
}
func (m *ReplyAnchorList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyAnchorList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyAnchorList proto.InternalMessageInfo

func (m *ReplyAnchorList) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplyAnchorList) GetPageMax() uint32 {
	if m != nil {
		return m.PageMax
	}
	return 0
}

func (m *ReplyAnchorList) GetPageNow() uint32 {
	if m != nil {
		return m.PageNow
	}
	return 0
}

func (m *ReplyAnchorList) GetList() []*AnchorInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *ReplyAnchorList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*AnchorInfo)(nil), "omo.msp.museum.AnchorInfo")
	proto.RegisterType((*ReqAnchorAdd)(nil), "omo.msp.museum.ReqAnchorAdd")
	proto.RegisterType((*ReqAnchorUpdate)(nil), "omo.msp.museum.ReqAnchorUpdate")
	proto.RegisterType((*ReplyAnchorOne)(nil), "omo.msp.museum.ReplyAnchorOne")
	proto.RegisterType((*ReplyAnchorList)(nil), "omo.msp.museum.ReplyAnchorList")
}

func init() {
	proto.RegisterFile("proto/museum/anchor.proto", fileDescriptor_f070abf93908957a)
}

var fileDescriptor_f070abf93908957a = []byte{
	// 652 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xcd, 0x4e, 0xdb, 0x4c,
	0x14, 0x8d, 0x63, 0xc7, 0xc0, 0x0d, 0x09, 0x9f, 0x46, 0x9f, 0xaa, 0x21, 0xfc, 0x45, 0x5e, 0x65,
	0x15, 0xa4, 0xb0, 0xa9, 0xd4, 0x15, 0x48, 0x6d, 0xda, 0x8a, 0x42, 0xe5, 0xa8, 0x9b, 0x6e, 0xd0,
	0xd4, 0x1e, 0x60, 0x44, 0xec, 0x31, 0xe3, 0x31, 0x94, 0x17, 0xe8, 0x33, 0xf4, 0x71, 0xfa, 0x4e,
	0x7d, 0x81, 0xea, 0xce, 0x38, 0x26, 0x86, 0x40, 0xb2, 0xf3, 0x99, 0x73, 0xe7, 0xdc, 0x73, 0xee,
	0x9d, 0x28, 0xb0, 0x9d, 0x29, 0xa9, 0xe5, 0x61, 0x52, 0xe4, 0xbc, 0x48, 0x0e, 0x59, 0x1a, 0x5d,
	0x4b, 0x35, 0x34, 0x67, 0xa4, 0x2b, 0x13, 0x39, 0x4c, 0xf2, 0x6c, 0x68, 0xc9, 0x5e, 0xbd, 0x34,
	0x92, 0x49, 0x22, 0x53, 0x5b, 0x1a, 0xfc, 0x72, 0x01, 0x8e, 0xcd, 0xdd, 0x4f, 0xe9, 0xa5, 0x24,
	0xff, 0x81, 0x5b, 0x88, 0x98, 0x3a, 0x7d, 0x67, 0xb0, 0x11, 0xe2, 0x27, 0xe9, 0x42, 0x53, 0xc4,
	0xb4, 0xd9, 0x77, 0x06, 0x5e, 0xd8, 0x14, 0x31, 0xa1, 0xb0, 0x16, 0x29, 0xce, 0x34, 0x8f, 0xa9,
	0xdb, 0x77, 0x06, 0x6e, 0x38, 0x83, 0xc8, 0x14, 0x59, 0x6c, 0x18, 0xcf, 0x32, 0x25, 0xac, 0xee,
	0x48, 0x45, 0x5b, 0x46, 0x79, 0x06, 0x49, 0x0f, 0xd6, 0x65, 0xc6, 0x95, 0xa1, 0x7c, 0x43, 0x55,
	0x98, 0x10, 0xf0, 0x52, 0x96, 0x70, 0xba, 0x66, 0xce, 0xcd, 0x37, 0x79, 0x03, 0xbe, 0xe2, 0x09,
	0x53, 0x37, 0x74, 0xdd, 0x9c, 0x96, 0x88, 0xfc, 0x0f, 0xad, 0x48, 0xde, 0x71, 0x45, 0x37, 0xcc,
	0xb1, 0x05, 0x58, 0x9d, 0x31, 0xc5, 0x53, 0x4d, 0xc1, 0x56, 0x5b, 0x84, 0x5d, 0x33, 0x96, 0x4a,
	0xc5, 0x12, 0x46, 0xdb, 0xb6, 0xeb, 0x0c, 0x63, 0xd7, 0xa9, 0x48, 0x6f, 0xe8, 0xa6, 0xed, 0x8a,
	0xdf, 0xa8, 0x2e, 0xef, 0x53, 0xae, 0x68, 0xc7, 0xaa, 0x1b, 0x40, 0xde, 0xc2, 0x7a, 0x26, 0x73,
	0xa1, 0x85, 0x4c, 0x69, 0xb7, 0xef, 0x0c, 0xda, 0xa3, 0xdd, 0x61, 0x7d, 0xf0, 0xc3, 0xaf, 0x25,
	0x8f, 0xb3, 0x0d, 0xab, 0x6a, 0xec, 0xa1, 0xd9, 0x55, 0x4e, 0xb7, 0xfa, 0x2e, 0xf6, 0xc0, 0xef,
	0xe0, 0xb7, 0x03, 0x9b, 0x21, 0xbf, 0xb5, 0xbb, 0x38, 0x8e, 0xe3, 0x2a, 0xbe, 0x53, 0x8f, 0x5f,
	0x06, 0x6a, 0xd6, 0x02, 0x3d, 0x8e, 0xc5, 0x7d, 0x3a, 0x16, 0x6b, 0xdc, 0x9b, 0x37, 0x3e, 0x3f,
	0xf4, 0xd6, 0xf3, 0xa1, 0x1b, 0x6b, 0xfe, 0x9c, 0xb5, 0x1b, 0xd8, 0xaa, 0x9c, 0x7d, 0x33, 0x2b,
	0x5d, 0xf0, 0x4e, 0x66, 0x76, 0x9b, 0x0b, 0xb7, 0x55, 0xb7, 0x35, 0x6f, 0xc0, 0xab, 0x1b, 0x08,
	0x0a, 0xe8, 0x86, 0x3c, 0x9b, 0x3e, 0xd8, 0x76, 0xe7, 0x29, 0x27, 0x43, 0xf0, 0x44, 0x7a, 0x29,
	0x4d, 0xb3, 0xf6, 0xa8, 0xf7, 0x74, 0xc6, 0x8f, 0xaf, 0x37, 0x34, 0x75, 0xe4, 0x08, 0xfc, 0x5c,
	0x33, 0x5d, 0xe4, 0xc6, 0x4b, 0x7b, 0xb4, 0xf3, 0xf4, 0x86, 0xd1, 0x9f, 0x98, 0x92, 0xb0, 0x2c,
	0x0d, 0xfe, 0x38, 0x18, 0xb2, 0xea, 0x7b, 0x2a, 0x72, 0x8d, 0xd3, 0xd3, 0x52, 0xb3, 0xa9, 0xe9,
	0xdc, 0x09, 0x2d, 0xc0, 0xc7, 0x9c, 0xb1, 0x2b, 0xfe, 0x85, 0xfd, 0x34, 0xfa, 0x9d, 0x70, 0x06,
	0x67, 0xcc, 0x99, 0xbc, 0x37, 0x79, 0x4b, 0xe6, 0x4c, 0xde, 0x63, 0x84, 0xa9, 0xc8, 0x35, 0xf5,
	0xfa, 0xee, 0xb2, 0x08, 0x58, 0x37, 0x17, 0xa1, 0xb5, 0x72, 0x84, 0xd1, 0x5f, 0x0f, 0x3a, 0x56,
	0x69, 0xc2, 0xd5, 0x9d, 0x88, 0x38, 0xf9, 0x08, 0xfe, 0x71, 0x1c, 0xe3, 0x0c, 0x77, 0x9f, 0x0b,
	0x3c, 0x3e, 0xb5, 0xde, 0xfe, 0x42, 0xf9, 0x6a, 0x03, 0x41, 0x83, 0x8c, 0xc1, 0x1f, 0x73, 0x8d,
	0x4a, 0x0b, 0xac, 0xdc, 0x16, 0x3c, 0xd7, 0xe8, 0x7e, 0x05, 0xa1, 0xf7, 0xb0, 0x11, 0xf2, 0x44,
	0xde, 0xf1, 0xa5, 0x5a, 0xdb, 0x0b, 0xb5, 0x90, 0x0a, 0x1a, 0x98, 0x6c, 0xc2, 0x99, 0x8a, 0xae,
	0x5f, 0xd7, 0x38, 0x78, 0xc5, 0x0f, 0xae, 0x38, 0x68, 0x90, 0x09, 0x6c, 0x8d, 0xb9, 0x46, 0x70,
	0xf2, 0xf0, 0x41, 0x4c, 0x35, 0x57, 0x64, 0xef, 0x05, 0x49, 0x4b, 0xaf, 0x22, 0x7a, 0x0e, 0x9b,
	0x63, 0xae, 0x71, 0x3f, 0x22, 0xd7, 0x22, 0x5a, 0xa6, 0xb8, 0xff, 0xe2, 0x7a, 0xcd, 0xf5, 0xa0,
	0x41, 0x3e, 0x03, 0xd8, 0x5f, 0xde, 0x09, 0xcb, 0x39, 0x39, 0x78, 0x71, 0x9b, 0xb6, 0xe8, 0xf5,
	0xd9, 0x9d, 0x42, 0xb7, 0xd4, 0x5a, 0x16, 0x78, 0x05, 0xb5, 0x93, 0xbd, 0xef, 0x3b, 0xf3, 0xff,
	0x2e, 0xef, 0x64, 0x22, 0x2f, 0x92, 0x3c, 0xbb, 0xb0, 0xf0, 0x87, 0x6f, 0xc8, 0xa3, 0x7f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x9e, 0xc6, 0xfd, 0x6b, 0xae, 0x06, 0x00, 0x00,
}
