// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/museum/area.proto

package omo_msp_museum

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AreaInfo struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Created              uint64   `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Updated              uint64   `protobuf:"varint,5,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string   `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string   `protobuf:"bytes,7,opt,name=operator,proto3" json:"operator,omitempty"`
	Remark               string   `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	Owner                string   `protobuf:"bytes,9,opt,name=owner,proto3" json:"owner,omitempty"`
	Parent               string   `protobuf:"bytes,10,opt,name=parent,proto3" json:"parent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AreaInfo) Reset()         { *m = AreaInfo{} }
func (m *AreaInfo) String() string { return proto.CompactTextString(m) }
func (*AreaInfo) ProtoMessage()    {}
func (*AreaInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdaab6c3b1c511c0, []int{0}
}

func (m *AreaInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AreaInfo.Unmarshal(m, b)
}
func (m *AreaInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AreaInfo.Marshal(b, m, deterministic)
}
func (m *AreaInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AreaInfo.Merge(m, src)
}
func (m *AreaInfo) XXX_Size() int {
	return xxx_messageInfo_AreaInfo.Size(m)
}
func (m *AreaInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AreaInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AreaInfo proto.InternalMessageInfo

func (m *AreaInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AreaInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *AreaInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AreaInfo) GetCreated() uint64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *AreaInfo) GetUpdated() uint64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *AreaInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *AreaInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *AreaInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *AreaInfo) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *AreaInfo) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

type ReqAreaAdd struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Parent               string   `protobuf:"bytes,4,opt,name=parent,proto3" json:"parent,omitempty"`
	Operator             string   `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqAreaAdd) Reset()         { *m = ReqAreaAdd{} }
func (m *ReqAreaAdd) String() string { return proto.CompactTextString(m) }
func (*ReqAreaAdd) ProtoMessage()    {}
func (*ReqAreaAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdaab6c3b1c511c0, []int{1}
}

func (m *ReqAreaAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqAreaAdd.Unmarshal(m, b)
}
func (m *ReqAreaAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqAreaAdd.Marshal(b, m, deterministic)
}
func (m *ReqAreaAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqAreaAdd.Merge(m, src)
}
func (m *ReqAreaAdd) XXX_Size() int {
	return xxx_messageInfo_ReqAreaAdd.Size(m)
}
func (m *ReqAreaAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqAreaAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqAreaAdd proto.InternalMessageInfo

func (m *ReqAreaAdd) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqAreaAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqAreaAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqAreaAdd) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *ReqAreaAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type ReqAreaBase struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqAreaBase) Reset()         { *m = ReqAreaBase{} }
func (m *ReqAreaBase) String() string { return proto.CompactTextString(m) }
func (*ReqAreaBase) ProtoMessage()    {}
func (*ReqAreaBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdaab6c3b1c511c0, []int{2}
}

func (m *ReqAreaBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqAreaBase.Unmarshal(m, b)
}
func (m *ReqAreaBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqAreaBase.Marshal(b, m, deterministic)
}
func (m *ReqAreaBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqAreaBase.Merge(m, src)
}
func (m *ReqAreaBase) XXX_Size() int {
	return xxx_messageInfo_ReqAreaBase.Size(m)
}
func (m *ReqAreaBase) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqAreaBase.DiscardUnknown(m)
}

var xxx_messageInfo_ReqAreaBase proto.InternalMessageInfo

func (m *ReqAreaBase) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqAreaBase) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqAreaBase) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

type ReplyAreaInfo struct {
	Info                 *AreaInfo    `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyAreaInfo) Reset()         { *m = ReplyAreaInfo{} }
func (m *ReplyAreaInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyAreaInfo) ProtoMessage()    {}
func (*ReplyAreaInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdaab6c3b1c511c0, []int{3}
}

func (m *ReplyAreaInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyAreaInfo.Unmarshal(m, b)
}
func (m *ReplyAreaInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyAreaInfo.Marshal(b, m, deterministic)
}
func (m *ReplyAreaInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyAreaInfo.Merge(m, src)
}
func (m *ReplyAreaInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyAreaInfo.Size(m)
}
func (m *ReplyAreaInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyAreaInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyAreaInfo proto.InternalMessageInfo

func (m *ReplyAreaInfo) GetInfo() *AreaInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReplyAreaInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReplyAreaList struct {
	Total                uint32       `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Page                 uint32       `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Pages                uint32       `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Number               uint32       `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	List                 []*AreaInfo  `protobuf:"bytes,5,rep,name=list,proto3" json:"list,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyAreaList) Reset()         { *m = ReplyAreaList{} }
func (m *ReplyAreaList) String() string { return proto.CompactTextString(m) }
func (*ReplyAreaList) ProtoMessage()    {}
func (*ReplyAreaList) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdaab6c3b1c511c0, []int{4}
}

func (m *ReplyAreaList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyAreaList.Unmarshal(m, b)
}
func (m *ReplyAreaList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyAreaList.Marshal(b, m, deterministic)
}
func (m *ReplyAreaList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyAreaList.Merge(m, src)
}
func (m *ReplyAreaList) XXX_Size() int {
	return xxx_messageInfo_ReplyAreaList.Size(m)
}
func (m *ReplyAreaList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyAreaList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyAreaList proto.InternalMessageInfo

func (m *ReplyAreaList) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplyAreaList) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ReplyAreaList) GetPages() uint32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *ReplyAreaList) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *ReplyAreaList) GetList() []*AreaInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *ReplyAreaList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*AreaInfo)(nil), "omo.msp.museum.AreaInfo")
	proto.RegisterType((*ReqAreaAdd)(nil), "omo.msp.museum.ReqAreaAdd")
	proto.RegisterType((*ReqAreaBase)(nil), "omo.msp.museum.ReqAreaBase")
	proto.RegisterType((*ReplyAreaInfo)(nil), "omo.msp.museum.ReplyAreaInfo")
	proto.RegisterType((*ReplyAreaList)(nil), "omo.msp.museum.ReplyAreaList")
}

func init() {
	proto.RegisterFile("proto/museum/area.proto", fileDescriptor_cdaab6c3b1c511c0)
}

var fileDescriptor_cdaab6c3b1c511c0 = []byte{
	// 559 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4f, 0x6f, 0xda, 0x4e,
	0x10, 0x8d, 0xc1, 0x38, 0x30, 0xfc, 0xe0, 0x57, 0xad, 0xaa, 0xd6, 0x01, 0x51, 0x21, 0x9f, 0x72,
	0xa8, 0x88, 0x44, 0x8e, 0x3d, 0x81, 0x94, 0xa0, 0xaa, 0x91, 0xa2, 0x1a, 0xf5, 0xd2, 0x4b, 0xb4,
	0xc1, 0x93, 0xd6, 0x2a, 0xeb, 0x75, 0xd6, 0xeb, 0x54, 0xb9, 0xf6, 0xe3, 0xf5, 0x7b, 0xf4, 0xde,
	0x8f, 0x50, 0xed, 0xac, 0x0d, 0xa6, 0xe1, 0x4f, 0xd4, 0x13, 0x7e, 0xfb, 0xde, 0xbc, 0x99, 0xb7,
	0x63, 0x0c, 0xaf, 0x53, 0x25, 0xb5, 0x3c, 0x13, 0x79, 0x86, 0xb9, 0x38, 0xe3, 0x0a, 0xf9, 0x88,
	0x4e, 0x58, 0x57, 0x0a, 0x39, 0x12, 0x59, 0x3a, 0xb2, 0x54, 0xef, 0x64, 0x43, 0xb8, 0x90, 0x42,
	0xc8, 0xc4, 0x4a, 0x83, 0xdf, 0x0e, 0x34, 0x27, 0x0a, 0xf9, 0xfb, 0xe4, 0x4e, 0xb2, 0x2e, 0xd4,
	0xe2, 0xc8, 0x77, 0x86, 0xce, 0xa9, 0x1b, 0xd6, 0xe2, 0x88, 0xbd, 0x80, 0x7a, 0x1e, 0x47, 0x7e,
	0x6d, 0xe8, 0x9c, 0xb6, 0x42, 0xf3, 0xc8, 0x18, 0xb8, 0x09, 0x17, 0xe8, 0xd7, 0xe9, 0x88, 0x9e,
	0x99, 0x0f, 0xc7, 0x0b, 0x85, 0x5c, 0x63, 0xe4, 0xbb, 0x54, 0x5a, 0x42, 0xc3, 0xe4, 0x69, 0x44,
	0x4c, 0xc3, 0x32, 0x05, 0x5c, 0xd5, 0x48, 0xe5, 0x7b, 0x64, 0x55, 0x42, 0xd6, 0x83, 0xa6, 0x4c,
	0x51, 0x11, 0x75, 0x4c, 0xd4, 0x0a, 0xb3, 0x57, 0xe0, 0x29, 0x14, 0x5c, 0x7d, 0xf3, 0x9b, 0xc4,
	0x14, 0x88, 0xbd, 0x84, 0x86, 0xfc, 0x9e, 0xa0, 0xf2, 0x5b, 0x74, 0x6c, 0x81, 0x51, 0xa7, 0x5c,
	0x61, 0xa2, 0x7d, 0xb0, 0x6a, 0x8b, 0x82, 0x1f, 0x0e, 0x40, 0x88, 0xf7, 0x26, 0xf5, 0x24, 0x8a,
	0xd6, 0xc5, 0x4e, 0xb5, 0xb8, 0x0c, 0x5a, 0xab, 0x04, 0x5d, 0xb7, 0xaf, 0x6f, 0xb4, 0x5f, 0x37,
	0x72, 0xab, 0x8d, 0x36, 0xa2, 0x34, 0x36, 0xa3, 0x04, 0x1f, 0xa0, 0x5d, 0xcc, 0x30, 0xe5, 0x19,
	0x96, 0x37, 0xed, 0x3c, 0xbd, 0xe9, 0x67, 0x0c, 0x10, 0x28, 0xe8, 0x84, 0x98, 0x2e, 0x1f, 0x57,
	0x8b, 0x7c, 0x0b, 0x6e, 0x9c, 0xdc, 0x49, 0xf2, 0x6b, 0x8f, 0xfd, 0xd1, 0xe6, 0xfb, 0x30, 0x2a,
	0x75, 0x21, 0xa9, 0xd8, 0x39, 0x78, 0x99, 0xe6, 0x3a, 0xcf, 0xa8, 0x59, 0x7b, 0xdc, 0xff, 0x5b,
	0x4f, 0xe6, 0x73, 0x92, 0x84, 0x85, 0x34, 0xf8, 0xe9, 0x54, 0x9a, 0x5e, 0xc5, 0x99, 0x36, 0x17,
	0xa9, 0xa5, 0xe6, 0x4b, 0xea, 0xda, 0x09, 0x2d, 0x30, 0x39, 0x52, 0xfe, 0xc5, 0xe6, 0xe8, 0x84,
	0xf4, 0x6c, 0x94, 0xe6, 0x37, 0xa3, 0x18, 0x9d, 0xd0, 0x02, 0x93, 0x2e, 0xc9, 0xc5, 0x2d, 0x2a,
	0xba, 0xc6, 0x4e, 0x58, 0x20, 0x13, 0x66, 0x19, 0x67, 0xda, 0x6f, 0x0c, 0xeb, 0xfb, 0xc3, 0x18,
	0x55, 0x25, 0x8c, 0xf7, 0xec, 0x30, 0xe3, 0x5f, 0x2e, 0xb4, 0x8d, 0xcf, 0x1c, 0xd5, 0x43, 0xbc,
	0x40, 0x76, 0x01, 0xde, 0x24, 0x8a, 0xae, 0x13, 0x64, 0xbd, 0xa7, 0xe5, 0xe5, 0x9b, 0xd3, 0x1b,
	0x6c, 0xb5, 0x2e, 0xe7, 0x09, 0x8e, 0xd8, 0x25, 0x78, 0x33, 0xd4, 0xc6, 0x66, 0xcb, 0x14, 0xf7,
	0x39, 0x66, 0xda, 0x08, 0x0f, 0xfb, 0x5c, 0x40, 0x2b, 0x44, 0x21, 0x1f, 0xf0, 0xa0, 0xd5, 0xc9,
	0x56, 0xab, 0xf5, 0x38, 0x73, 0xe4, 0x6a, 0xf1, 0xf5, 0x5f, 0xc7, 0x31, 0x6b, 0x0e, 0x8e, 0xd8,
	0x47, 0xf8, 0x7f, 0x86, 0xda, 0x80, 0xe9, 0xe3, 0x65, 0xbc, 0xd4, 0xa8, 0xd8, 0x60, 0x87, 0xa1,
	0xa5, 0x0f, 0x5b, 0x5e, 0xc3, 0x7f, 0x33, 0xd4, 0x66, 0x2b, 0x71, 0xa6, 0xe3, 0xc5, 0x21, 0xbf,
	0x37, 0x3b, 0x97, 0x4a, 0xe5, 0x94, 0x15, 0x3e, 0xd1, 0xb7, 0x86, 0xfe, 0x5e, 0xfd, 0x1d, 0x5b,
	0x34, 0xe4, 0xfe, 0x3b, 0xbb, 0x82, 0x6e, 0xe1, 0x73, 0x28, 0xaa, 0x95, 0xed, 0x75, 0x9b, 0x0e,
	0x3e, 0xf7, 0xab, 0x9f, 0xe2, 0x77, 0x52, 0xc8, 0x1b, 0x91, 0xa5, 0x37, 0x16, 0xde, 0x7a, 0x44,
	0x9e, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0xf0, 0xca, 0x22, 0x30, 0xd9, 0x05, 0x00, 0x00,
}
