// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/museum/booth.proto

package omo_msp_museum

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BoothInfo struct {
	Id                   uint64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  string        `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string        `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Created              uint64        `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Updated              uint64        `protobuf:"varint,5,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string        `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string        `protobuf:"bytes,7,opt,name=operator,proto3" json:"operator,omitempty"`
	Remark               string        `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	Owner                string        `protobuf:"bytes,9,opt,name=owner,proto3" json:"owner,omitempty"`
	Parent               string        `protobuf:"bytes,10,opt,name=parent,proto3" json:"parent,omitempty"`
	Exhibit              string        `protobuf:"bytes,11,opt,name=exhibit,proto3" json:"exhibit,omitempty"`
	Position             *PositionInfo `protobuf:"bytes,12,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *BoothInfo) Reset()         { *m = BoothInfo{} }
func (m *BoothInfo) String() string { return proto.CompactTextString(m) }
func (*BoothInfo) ProtoMessage()    {}
func (*BoothInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b315febb412b4e4, []int{0}
}

func (m *BoothInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoothInfo.Unmarshal(m, b)
}
func (m *BoothInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoothInfo.Marshal(b, m, deterministic)
}
func (m *BoothInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoothInfo.Merge(m, src)
}
func (m *BoothInfo) XXX_Size() int {
	return xxx_messageInfo_BoothInfo.Size(m)
}
func (m *BoothInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BoothInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BoothInfo proto.InternalMessageInfo

func (m *BoothInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BoothInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *BoothInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BoothInfo) GetCreated() uint64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *BoothInfo) GetUpdated() uint64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *BoothInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *BoothInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *BoothInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *BoothInfo) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *BoothInfo) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *BoothInfo) GetExhibit() string {
	if m != nil {
		return m.Exhibit
	}
	return ""
}

func (m *BoothInfo) GetPosition() *PositionInfo {
	if m != nil {
		return m.Position
	}
	return nil
}

type ReqBoothAdd struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Parent               string   `protobuf:"bytes,4,opt,name=parent,proto3" json:"parent,omitempty"`
	Operator             string   `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqBoothAdd) Reset()         { *m = ReqBoothAdd{} }
func (m *ReqBoothAdd) String() string { return proto.CompactTextString(m) }
func (*ReqBoothAdd) ProtoMessage()    {}
func (*ReqBoothAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b315febb412b4e4, []int{1}
}

func (m *ReqBoothAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqBoothAdd.Unmarshal(m, b)
}
func (m *ReqBoothAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqBoothAdd.Marshal(b, m, deterministic)
}
func (m *ReqBoothAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqBoothAdd.Merge(m, src)
}
func (m *ReqBoothAdd) XXX_Size() int {
	return xxx_messageInfo_ReqBoothAdd.Size(m)
}
func (m *ReqBoothAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqBoothAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqBoothAdd proto.InternalMessageInfo

func (m *ReqBoothAdd) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqBoothAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqBoothAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqBoothAdd) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *ReqBoothAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type ReqBoothUpdate struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Operator             string   `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	Remark               string   `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqBoothUpdate) Reset()         { *m = ReqBoothUpdate{} }
func (m *ReqBoothUpdate) String() string { return proto.CompactTextString(m) }
func (*ReqBoothUpdate) ProtoMessage()    {}
func (*ReqBoothUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b315febb412b4e4, []int{2}
}

func (m *ReqBoothUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqBoothUpdate.Unmarshal(m, b)
}
func (m *ReqBoothUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqBoothUpdate.Marshal(b, m, deterministic)
}
func (m *ReqBoothUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqBoothUpdate.Merge(m, src)
}
func (m *ReqBoothUpdate) XXX_Size() int {
	return xxx_messageInfo_ReqBoothUpdate.Size(m)
}
func (m *ReqBoothUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqBoothUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqBoothUpdate proto.InternalMessageInfo

func (m *ReqBoothUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqBoothUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqBoothUpdate) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqBoothUpdate) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

type ReplyBoothInfo struct {
	Info                 *BoothInfo   `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyBoothInfo) Reset()         { *m = ReplyBoothInfo{} }
func (m *ReplyBoothInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyBoothInfo) ProtoMessage()    {}
func (*ReplyBoothInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b315febb412b4e4, []int{3}
}

func (m *ReplyBoothInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyBoothInfo.Unmarshal(m, b)
}
func (m *ReplyBoothInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyBoothInfo.Marshal(b, m, deterministic)
}
func (m *ReplyBoothInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyBoothInfo.Merge(m, src)
}
func (m *ReplyBoothInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyBoothInfo.Size(m)
}
func (m *ReplyBoothInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyBoothInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyBoothInfo proto.InternalMessageInfo

func (m *ReplyBoothInfo) GetInfo() *BoothInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReplyBoothInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReplyBoothList struct {
	Total                uint32       `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Pages                uint32       `protobuf:"varint,2,opt,name=pages,proto3" json:"pages,omitempty"`
	Page                 uint32       `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Number               uint32       `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	List                 []*BoothInfo `protobuf:"bytes,6,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyBoothList) Reset()         { *m = ReplyBoothList{} }
func (m *ReplyBoothList) String() string { return proto.CompactTextString(m) }
func (*ReplyBoothList) ProtoMessage()    {}
func (*ReplyBoothList) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b315febb412b4e4, []int{4}
}

func (m *ReplyBoothList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyBoothList.Unmarshal(m, b)
}
func (m *ReplyBoothList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyBoothList.Marshal(b, m, deterministic)
}
func (m *ReplyBoothList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyBoothList.Merge(m, src)
}
func (m *ReplyBoothList) XXX_Size() int {
	return xxx_messageInfo_ReplyBoothList.Size(m)
}
func (m *ReplyBoothList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyBoothList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyBoothList proto.InternalMessageInfo

func (m *ReplyBoothList) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplyBoothList) GetPages() uint32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *ReplyBoothList) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ReplyBoothList) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *ReplyBoothList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyBoothList) GetList() []*BoothInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*BoothInfo)(nil), "omo.msp.museum.BoothInfo")
	proto.RegisterType((*ReqBoothAdd)(nil), "omo.msp.museum.ReqBoothAdd")
	proto.RegisterType((*ReqBoothUpdate)(nil), "omo.msp.museum.ReqBoothUpdate")
	proto.RegisterType((*ReplyBoothInfo)(nil), "omo.msp.museum.ReplyBoothInfo")
	proto.RegisterType((*ReplyBoothList)(nil), "omo.msp.museum.ReplyBoothList")
}

func init() {
	proto.RegisterFile("proto/museum/booth.proto", fileDescriptor_3b315febb412b4e4)
}

var fileDescriptor_3b315febb412b4e4 = []byte{
	// 599 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x41, 0x6f, 0xda, 0x30,
	0x14, 0x6e, 0x20, 0xa4, 0xc5, 0x14, 0x36, 0x59, 0xd3, 0xe4, 0xb6, 0x6b, 0x85, 0x72, 0xe2, 0x32,
	0x2a, 0xd1, 0xcb, 0xa4, 0x9d, 0x8a, 0xb4, 0xa1, 0x4a, 0x95, 0x3a, 0x19, 0xed, 0xb2, 0x4b, 0x15,
	0xc8, 0xeb, 0xf0, 0x86, 0xe3, 0xcc, 0x71, 0xba, 0xf5, 0xbc, 0xdf, 0xb6, 0xdb, 0x7e, 0xcb, 0x7e,
	0xc3, 0xe4, 0xe7, 0x10, 0x42, 0x07, 0x03, 0xf5, 0xe6, 0xcf, 0xef, 0xf3, 0xf7, 0xbe, 0xf7, 0xbd,
	0x20, 0x08, 0x4b, 0xb5, 0x32, 0xea, 0x5c, 0xe6, 0x19, 0xe4, 0xf2, 0x7c, 0xa2, 0x94, 0x99, 0xf5,
	0xf1, 0x8a, 0x76, 0x94, 0x54, 0x7d, 0x99, 0xa5, 0x7d, 0x57, 0x3b, 0x3e, 0x5a, 0x61, 0x4e, 0x95,
	0x94, 0x2a, 0x71, 0xd4, 0xf0, 0x57, 0x8d, 0x34, 0x87, 0xf6, 0xe9, 0x55, 0x72, 0xa7, 0x68, 0x87,
	0xd4, 0x44, 0xcc, 0xbc, 0xae, 0xd7, 0xf3, 0x79, 0x4d, 0xc4, 0xf4, 0x39, 0xa9, 0xe7, 0x22, 0x66,
	0xb5, 0xae, 0xd7, 0x6b, 0x72, 0x7b, 0xa4, 0x94, 0xf8, 0x49, 0x24, 0x81, 0xd5, 0xf1, 0x0a, 0xcf,
	0x94, 0x91, 0xfd, 0xa9, 0x86, 0xc8, 0x40, 0xcc, 0x7c, 0x7c, 0xba, 0x80, 0xb6, 0x92, 0xa7, 0x31,
	0x56, 0x1a, 0xae, 0x52, 0xc0, 0xf2, 0x8d, 0xd2, 0x2c, 0x40, 0xa9, 0x05, 0xa4, 0xc7, 0xe4, 0x40,
	0xa5, 0xa0, 0xb1, 0xb4, 0x8f, 0xa5, 0x12, 0xd3, 0x97, 0x24, 0xd0, 0x20, 0x23, 0xfd, 0x95, 0x1d,
	0x60, 0xa5, 0x40, 0xf4, 0x05, 0x69, 0xa8, 0xef, 0x09, 0x68, 0xd6, 0xc4, 0x6b, 0x07, 0x2c, 0x3b,
	0x8d, 0x34, 0x24, 0x86, 0x11, 0xc7, 0x76, 0xc8, 0xf6, 0x86, 0x1f, 0x33, 0x31, 0x11, 0x86, 0xb5,
	0x5c, 0xef, 0x02, 0xd2, 0x37, 0xe4, 0x20, 0x55, 0x99, 0x30, 0x42, 0x25, 0xec, 0xb0, 0xeb, 0xf5,
	0x5a, 0x83, 0x57, 0xfd, 0xd5, 0x2c, 0xfb, 0x1f, 0x8a, 0xba, 0xcd, 0x8b, 0x97, 0xec, 0xf0, 0xa7,
	0x47, 0x5a, 0x1c, 0xbe, 0x61, 0x94, 0x97, 0x71, 0xbc, 0x74, 0xe4, 0x55, 0x1d, 0x2d, 0xd2, 0xab,
	0x55, 0xd2, 0x5b, 0xce, 0x54, 0x5f, 0x99, 0x69, 0xe9, 0xde, 0x5f, 0x71, 0x5f, 0xcd, 0xa7, 0xb1,
	0x9a, 0x4f, 0xf8, 0x85, 0x74, 0x16, 0x26, 0x3e, 0x62, 0xd0, 0x8b, 0x0d, 0x7a, 0xff, 0x6e, 0xb0,
	0xea, 0xa1, 0xaa, 0x59, 0xdf, 0x98, 0xb9, 0x5f, 0xf5, 0x17, 0x1a, 0xdb, 0x2b, 0x9d, 0x3f, 0x2c,
	0xbf, 0x9e, 0xd7, 0xc4, 0x17, 0xc9, 0x9d, 0xc2, 0x66, 0xad, 0xc1, 0xd1, 0xe3, 0xe4, 0x4a, 0x22,
	0x47, 0x1a, 0xbd, 0x20, 0x41, 0x66, 0x22, 0x93, 0x67, 0x68, 0xa5, 0x35, 0x38, 0x79, 0xfc, 0x00,
	0xe5, 0xc7, 0x48, 0xe1, 0x05, 0x35, 0xfc, 0xed, 0x55, 0xdb, 0x5e, 0x8b, 0xcc, 0xd8, 0xa8, 0x8d,
	0x32, 0xd1, 0x1c, 0xfb, 0xb6, 0xb9, 0x03, 0xf6, 0x36, 0x8d, 0x3e, 0x83, 0x13, 0x6f, 0x73, 0x07,
	0xec, 0xf0, 0xf6, 0x80, 0x43, 0xb6, 0x39, 0x9e, 0xed, 0x80, 0x49, 0x2e, 0x27, 0xa0, 0x71, 0xc0,
	0x36, 0x2f, 0x50, 0xc5, 0x5f, 0x63, 0x67, 0x7f, 0x36, 0x83, 0xb9, 0xc8, 0x0c, 0x0b, 0xba, 0xf5,
	0x2d, 0x19, 0x58, 0xda, 0xe0, 0x8f, 0x4f, 0x0e, 0xf1, 0x6e, 0x0c, 0xfa, 0x5e, 0x4c, 0x81, 0x8e,
	0x48, 0x70, 0x19, 0xc7, 0x37, 0x09, 0xd0, 0x35, 0xed, 0xca, 0xcf, 0xeb, 0xf8, 0x6c, 0xad, 0x97,
	0x52, 0x3d, 0xdc, 0xb3, 0x42, 0x23, 0x30, 0x9b, 0x84, 0x72, 0xc8, 0x8c, 0x25, 0xee, 0x20, 0xf4,
	0x8e, 0x34, 0x39, 0x48, 0x75, 0x0f, 0x5b, 0xb5, 0x8e, 0xd6, 0x6a, 0x2d, 0xfd, 0x8c, 0x21, 0xd2,
	0xd3, 0xd9, 0x93, 0xfd, 0xd8, 0x65, 0x87, 0x7b, 0x94, 0x93, 0x67, 0x23, 0x30, 0x16, 0x0c, 0x1f,
	0xde, 0x8b, 0xb9, 0x01, 0x4d, 0x4f, 0x37, 0x28, 0xba, 0xf2, 0x0e, 0x9a, 0x37, 0xe4, 0x70, 0x04,
	0xc6, 0xae, 0x52, 0x64, 0x46, 0x4c, 0x9f, 0x26, 0x58, 0x3e, 0x0f, 0xf7, 0xe8, 0x15, 0x21, 0xee,
	0x07, 0x38, 0x8c, 0x32, 0xa0, 0x67, 0x9b, 0x56, 0xe9, 0x38, 0xff, 0x0f, 0xee, 0x9a, 0x74, 0x0a,
	0xa9, 0x6d, 0xe3, 0xee, 0xa0, 0x36, 0x3c, 0xfd, 0x74, 0x52, 0xfd, 0x33, 0x78, 0xab, 0xa4, 0xba,
	0x95, 0x59, 0x7a, 0xeb, 0xe0, 0x24, 0xc0, 0xe2, 0xc5, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4d,
	0x28, 0x6e, 0x4f, 0x5c, 0x06, 0x00, 0x00,
}
