// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/museum/sandtable.proto

package omo_msp_museum

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SandtableInfo struct {
	Id                   uint64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  string         `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string         `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Created              uint64         `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Updated              uint64         `protobuf:"varint,5,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string         `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string         `protobuf:"bytes,7,opt,name=operator,proto3" json:"operator,omitempty"`
	Remark               string         `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	Owner                string         `protobuf:"bytes,9,opt,name=owner,proto3" json:"owner,omitempty"`
	Background           string         `protobuf:"bytes,10,opt,name=background,proto3" json:"background,omitempty"`
	Mask                 string         `protobuf:"bytes,11,opt,name=mask,proto3" json:"mask,omitempty"`
	Width                uint32         `protobuf:"varint,12,opt,name=width,proto3" json:"width,omitempty"`
	Height               uint32         `protobuf:"varint,13,opt,name=height,proto3" json:"height,omitempty"`
	Narrate              string         `protobuf:"bytes,14,opt,name=narrate,proto3" json:"narrate,omitempty"`
	Bgm                  string         `protobuf:"bytes,15,opt,name=bgm,proto3" json:"bgm,omitempty"`
	Status               uint32         `protobuf:"varint,16,opt,name=status,proto3" json:"status,omitempty"`
	Tags                 []string       `protobuf:"bytes,17,rep,name=tags,proto3" json:"tags,omitempty"`
	Path                 []*PathKeyInfo `protobuf:"bytes,18,rep,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SandtableInfo) Reset()         { *m = SandtableInfo{} }
func (m *SandtableInfo) String() string { return proto.CompactTextString(m) }
func (*SandtableInfo) ProtoMessage()    {}
func (*SandtableInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_45d599f279dedef9, []int{0}
}

func (m *SandtableInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SandtableInfo.Unmarshal(m, b)
}
func (m *SandtableInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SandtableInfo.Marshal(b, m, deterministic)
}
func (m *SandtableInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SandtableInfo.Merge(m, src)
}
func (m *SandtableInfo) XXX_Size() int {
	return xxx_messageInfo_SandtableInfo.Size(m)
}
func (m *SandtableInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SandtableInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SandtableInfo proto.InternalMessageInfo

func (m *SandtableInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SandtableInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *SandtableInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SandtableInfo) GetCreated() uint64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *SandtableInfo) GetUpdated() uint64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *SandtableInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *SandtableInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *SandtableInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *SandtableInfo) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *SandtableInfo) GetBackground() string {
	if m != nil {
		return m.Background
	}
	return ""
}

func (m *SandtableInfo) GetMask() string {
	if m != nil {
		return m.Mask
	}
	return ""
}

func (m *SandtableInfo) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *SandtableInfo) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *SandtableInfo) GetNarrate() string {
	if m != nil {
		return m.Narrate
	}
	return ""
}

func (m *SandtableInfo) GetBgm() string {
	if m != nil {
		return m.Bgm
	}
	return ""
}

func (m *SandtableInfo) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SandtableInfo) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *SandtableInfo) GetPath() []*PathKeyInfo {
	if m != nil {
		return m.Path
	}
	return nil
}

type PathKeyInfo struct {
	Scale                float32  `protobuf:"fixed32,1,opt,name=scale,proto3" json:"scale,omitempty"`
	Position             *Vector3 `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Rotation             *Vector3 `protobuf:"bytes,3,opt,name=rotation,proto3" json:"rotation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PathKeyInfo) Reset()         { *m = PathKeyInfo{} }
func (m *PathKeyInfo) String() string { return proto.CompactTextString(m) }
func (*PathKeyInfo) ProtoMessage()    {}
func (*PathKeyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_45d599f279dedef9, []int{1}
}

func (m *PathKeyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PathKeyInfo.Unmarshal(m, b)
}
func (m *PathKeyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PathKeyInfo.Marshal(b, m, deterministic)
}
func (m *PathKeyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PathKeyInfo.Merge(m, src)
}
func (m *PathKeyInfo) XXX_Size() int {
	return xxx_messageInfo_PathKeyInfo.Size(m)
}
func (m *PathKeyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PathKeyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PathKeyInfo proto.InternalMessageInfo

func (m *PathKeyInfo) GetScale() float32 {
	if m != nil {
		return m.Scale
	}
	return 0
}

func (m *PathKeyInfo) GetPosition() *Vector3 {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *PathKeyInfo) GetRotation() *Vector3 {
	if m != nil {
		return m.Rotation
	}
	return nil
}

type ReqSandtableAdd struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Operator             string   `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	Background           string   `protobuf:"bytes,5,opt,name=background,proto3" json:"background,omitempty"`
	Width                uint32   `protobuf:"varint,6,opt,name=width,proto3" json:"width,omitempty"`
	Height               uint32   `protobuf:"varint,7,opt,name=height,proto3" json:"height,omitempty"`
	Tags                 []string `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSandtableAdd) Reset()         { *m = ReqSandtableAdd{} }
func (m *ReqSandtableAdd) String() string { return proto.CompactTextString(m) }
func (*ReqSandtableAdd) ProtoMessage()    {}
func (*ReqSandtableAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_45d599f279dedef9, []int{2}
}

func (m *ReqSandtableAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSandtableAdd.Unmarshal(m, b)
}
func (m *ReqSandtableAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSandtableAdd.Marshal(b, m, deterministic)
}
func (m *ReqSandtableAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSandtableAdd.Merge(m, src)
}
func (m *ReqSandtableAdd) XXX_Size() int {
	return xxx_messageInfo_ReqSandtableAdd.Size(m)
}
func (m *ReqSandtableAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSandtableAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSandtableAdd proto.InternalMessageInfo

func (m *ReqSandtableAdd) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqSandtableAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqSandtableAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqSandtableAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqSandtableAdd) GetBackground() string {
	if m != nil {
		return m.Background
	}
	return ""
}

func (m *ReqSandtableAdd) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *ReqSandtableAdd) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ReqSandtableAdd) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ReqSandtableBase struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Operator             string   `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	Remark               string   `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSandtableBase) Reset()         { *m = ReqSandtableBase{} }
func (m *ReqSandtableBase) String() string { return proto.CompactTextString(m) }
func (*ReqSandtableBase) ProtoMessage()    {}
func (*ReqSandtableBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_45d599f279dedef9, []int{3}
}

func (m *ReqSandtableBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSandtableBase.Unmarshal(m, b)
}
func (m *ReqSandtableBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSandtableBase.Marshal(b, m, deterministic)
}
func (m *ReqSandtableBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSandtableBase.Merge(m, src)
}
func (m *ReqSandtableBase) XXX_Size() int {
	return xxx_messageInfo_ReqSandtableBase.Size(m)
}
func (m *ReqSandtableBase) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSandtableBase.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSandtableBase proto.InternalMessageInfo

func (m *ReqSandtableBase) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqSandtableBase) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqSandtableBase) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqSandtableBase) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

type ReqSandtableBG struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Asset                string   `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	Operator             string   `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	Width                uint32   `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Height               uint32   `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSandtableBG) Reset()         { *m = ReqSandtableBG{} }
func (m *ReqSandtableBG) String() string { return proto.CompactTextString(m) }
func (*ReqSandtableBG) ProtoMessage()    {}
func (*ReqSandtableBG) Descriptor() ([]byte, []int) {
	return fileDescriptor_45d599f279dedef9, []int{4}
}

func (m *ReqSandtableBG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSandtableBG.Unmarshal(m, b)
}
func (m *ReqSandtableBG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSandtableBG.Marshal(b, m, deterministic)
}
func (m *ReqSandtableBG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSandtableBG.Merge(m, src)
}
func (m *ReqSandtableBG) XXX_Size() int {
	return xxx_messageInfo_ReqSandtableBG.Size(m)
}
func (m *ReqSandtableBG) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSandtableBG.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSandtableBG proto.InternalMessageInfo

func (m *ReqSandtableBG) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqSandtableBG) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *ReqSandtableBG) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqSandtableBG) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *ReqSandtableBG) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type ReqSandtablePath struct {
	Uid                  string         `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Path                 []*PathKeyInfo `protobuf:"bytes,2,rep,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReqSandtablePath) Reset()         { *m = ReqSandtablePath{} }
func (m *ReqSandtablePath) String() string { return proto.CompactTextString(m) }
func (*ReqSandtablePath) ProtoMessage()    {}
func (*ReqSandtablePath) Descriptor() ([]byte, []int) {
	return fileDescriptor_45d599f279dedef9, []int{5}
}

func (m *ReqSandtablePath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSandtablePath.Unmarshal(m, b)
}
func (m *ReqSandtablePath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSandtablePath.Marshal(b, m, deterministic)
}
func (m *ReqSandtablePath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSandtablePath.Merge(m, src)
}
func (m *ReqSandtablePath) XXX_Size() int {
	return xxx_messageInfo_ReqSandtablePath.Size(m)
}
func (m *ReqSandtablePath) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSandtablePath.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSandtablePath proto.InternalMessageInfo

func (m *ReqSandtablePath) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqSandtablePath) GetPath() []*PathKeyInfo {
	if m != nil {
		return m.Path
	}
	return nil
}

type ReplySandtableInfo struct {
	Info                 *SandtableInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Status               *ReplyStatus   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReplySandtableInfo) Reset()         { *m = ReplySandtableInfo{} }
func (m *ReplySandtableInfo) String() string { return proto.CompactTextString(m) }
func (*ReplySandtableInfo) ProtoMessage()    {}
func (*ReplySandtableInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_45d599f279dedef9, []int{6}
}

func (m *ReplySandtableInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplySandtableInfo.Unmarshal(m, b)
}
func (m *ReplySandtableInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplySandtableInfo.Marshal(b, m, deterministic)
}
func (m *ReplySandtableInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplySandtableInfo.Merge(m, src)
}
func (m *ReplySandtableInfo) XXX_Size() int {
	return xxx_messageInfo_ReplySandtableInfo.Size(m)
}
func (m *ReplySandtableInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplySandtableInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplySandtableInfo proto.InternalMessageInfo

func (m *ReplySandtableInfo) GetInfo() *SandtableInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReplySandtableInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReplySandtableList struct {
	Total                uint32           `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Pages                uint32           `protobuf:"varint,2,opt,name=pages,proto3" json:"pages,omitempty"`
	Page                 uint32           `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Number               uint32           `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	Status               *ReplyStatus     `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	List                 []*SandtableInfo `protobuf:"bytes,6,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReplySandtableList) Reset()         { *m = ReplySandtableList{} }
func (m *ReplySandtableList) String() string { return proto.CompactTextString(m) }
func (*ReplySandtableList) ProtoMessage()    {}
func (*ReplySandtableList) Descriptor() ([]byte, []int) {
	return fileDescriptor_45d599f279dedef9, []int{7}
}

func (m *ReplySandtableList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplySandtableList.Unmarshal(m, b)
}
func (m *ReplySandtableList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplySandtableList.Marshal(b, m, deterministic)
}
func (m *ReplySandtableList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplySandtableList.Merge(m, src)
}
func (m *ReplySandtableList) XXX_Size() int {
	return xxx_messageInfo_ReplySandtableList.Size(m)
}
func (m *ReplySandtableList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplySandtableList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplySandtableList proto.InternalMessageInfo

func (m *ReplySandtableList) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplySandtableList) GetPages() uint32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *ReplySandtableList) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ReplySandtableList) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *ReplySandtableList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplySandtableList) GetList() []*SandtableInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*SandtableInfo)(nil), "omo.msp.museum.SandtableInfo")
	proto.RegisterType((*PathKeyInfo)(nil), "omo.msp.museum.PathKeyInfo")
	proto.RegisterType((*ReqSandtableAdd)(nil), "omo.msp.museum.ReqSandtableAdd")
	proto.RegisterType((*ReqSandtableBase)(nil), "omo.msp.museum.ReqSandtableBase")
	proto.RegisterType((*ReqSandtableBG)(nil), "omo.msp.museum.ReqSandtableBG")
	proto.RegisterType((*ReqSandtablePath)(nil), "omo.msp.museum.ReqSandtablePath")
	proto.RegisterType((*ReplySandtableInfo)(nil), "omo.msp.museum.ReplySandtableInfo")
	proto.RegisterType((*ReplySandtableList)(nil), "omo.msp.museum.ReplySandtableList")
}

func init() {
	proto.RegisterFile("proto/museum/sandtable.proto", fileDescriptor_45d599f279dedef9)
}

var fileDescriptor_45d599f279dedef9 = []byte{
	// 818 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x4f, 0x4f, 0xe3, 0x38,
	0x14, 0x27, 0x4d, 0x1a, 0x8a, 0x4b, 0x4b, 0xd7, 0x42, 0xbb, 0x06, 0x16, 0xb6, 0xca, 0xa9, 0xa7,
	0xa2, 0x6d, 0x8f, 0x7b, 0x02, 0x69, 0xb7, 0x5a, 0x81, 0xd4, 0x55, 0x10, 0x1c, 0xf6, 0x82, 0xdc,
	0xc4, 0xb4, 0x11, 0x75, 0x1c, 0x6c, 0x07, 0x84, 0xb4, 0xa7, 0xbd, 0xcf, 0xd7, 0x98, 0xcf, 0x32,
	0xd7, 0x91, 0xe6, 0x03, 0x8d, 0x6c, 0x27, 0x69, 0xd2, 0x96, 0xb6, 0xd2, 0xdc, 0xfc, 0x7b, 0xef,
	0xf9, 0xf7, 0xfe, 0xfc, 0x9e, 0xd3, 0x82, 0x5f, 0x13, 0xce, 0x24, 0xbb, 0xa4, 0xa9, 0x20, 0x29,
	0xbd, 0x14, 0x38, 0x0e, 0x25, 0x9e, 0xcc, 0x49, 0x5f, 0x9b, 0x61, 0x9b, 0x51, 0xd6, 0xa7, 0x22,
	0xe9, 0x1b, 0xff, 0xe9, 0x49, 0x25, 0x3a, 0x60, 0x94, 0xb2, 0xd8, 0x84, 0x7a, 0x5f, 0x6c, 0xd0,
	0xba, 0xcb, 0xaf, 0xff, 0x1d, 0x3f, 0x31, 0xd8, 0x06, 0xb5, 0x28, 0x44, 0x56, 0xd7, 0xea, 0x39,
	0x7e, 0x2d, 0x0a, 0x61, 0x07, 0xd8, 0x69, 0x14, 0xa2, 0x5a, 0xd7, 0xea, 0x1d, 0xf8, 0xea, 0x08,
	0x21, 0x70, 0x62, 0x4c, 0x09, 0xb2, 0xb5, 0x49, 0x9f, 0x21, 0x02, 0xfb, 0x01, 0x27, 0x58, 0x92,
	0x10, 0x39, 0xfa, 0x6a, 0x0e, 0x95, 0x27, 0x4d, 0x42, 0xed, 0xa9, 0x1b, 0x4f, 0x06, 0x8b, 0x3b,
	0x8c, 0x23, 0x57, 0x53, 0xe5, 0x10, 0x9e, 0x82, 0x06, 0x4b, 0x08, 0xd7, 0xae, 0x7d, 0xed, 0x2a,
	0x30, 0xfc, 0x19, 0xb8, 0x9c, 0x50, 0xcc, 0x9f, 0x51, 0x43, 0x7b, 0x32, 0x04, 0x8f, 0x41, 0x9d,
	0xbd, 0xc5, 0x84, 0xa3, 0x03, 0x6d, 0x36, 0x00, 0x5e, 0x00, 0x30, 0xc1, 0xc1, 0xf3, 0x94, 0xb3,
	0x34, 0x0e, 0x11, 0xd0, 0xae, 0x92, 0x45, 0xf5, 0x42, 0xb1, 0x78, 0x46, 0x4d, 0xd3, 0x8b, 0x3a,
	0x2b, 0xa6, 0xb7, 0x28, 0x94, 0x33, 0x74, 0xd8, 0xb5, 0x7a, 0x2d, 0xdf, 0x00, 0x95, 0x77, 0x46,
	0xa2, 0xe9, 0x4c, 0xa2, 0x96, 0x36, 0x67, 0x48, 0x75, 0x11, 0x63, 0xce, 0xb1, 0x24, 0xa8, 0x6d,
	0xba, 0xc8, 0xa0, 0x9a, 0xdc, 0x64, 0x4a, 0xd1, 0x91, 0x99, 0xdc, 0x64, 0x4a, 0x15, 0x87, 0x90,
	0x58, 0xa6, 0x02, 0x75, 0x0c, 0x87, 0x41, 0xaa, 0x0a, 0x89, 0xa7, 0x02, 0xfd, 0xd4, 0xb5, 0x55,
	0x15, 0xea, 0x0c, 0x2f, 0x81, 0x93, 0x60, 0x39, 0x43, 0xb0, 0x6b, 0xf7, 0x9a, 0x83, 0xb3, 0x7e,
	0x55, 0xd3, 0xfe, 0x3f, 0x58, 0xce, 0x6e, 0xc8, 0xbb, 0x92, 0xcc, 0xd7, 0x81, 0xde, 0x27, 0x0b,
	0x34, 0x4b, 0x56, 0xd5, 0x86, 0x08, 0xf0, 0x9c, 0x68, 0x2d, 0x6b, 0xbe, 0x01, 0x70, 0x08, 0x1a,
	0x09, 0x13, 0x91, 0x8c, 0x58, 0xac, 0x35, 0x6d, 0x0e, 0x7e, 0x59, 0xa6, 0x7e, 0x20, 0x81, 0x64,
	0x7c, 0xe8, 0x17, 0x81, 0xea, 0x12, 0x67, 0x12, 0xeb, 0x4b, 0xf6, 0x96, 0x4b, 0x79, 0xa0, 0xf7,
	0xd5, 0x02, 0x47, 0x3e, 0x79, 0x29, 0xb6, 0xeb, 0x2a, 0x0c, 0x17, 0x22, 0x59, 0x65, 0x91, 0xf2,
	0x85, 0xaa, 0x95, 0x16, 0x6a, 0x21, 0xb3, 0x5d, 0x91, 0xb9, 0xbc, 0x1a, 0xce, 0xd2, 0x6a, 0x54,
	0xc5, 0xae, 0xaf, 0x88, 0x5d, 0x08, 0xeb, 0xae, 0x17, 0x76, 0xbf, 0x22, 0x6c, 0x2e, 0x4a, 0x63,
	0x21, 0x8a, 0x37, 0x07, 0x9d, 0x72, 0x4b, 0xd7, 0x58, 0x90, 0xfc, 0x81, 0x58, 0xab, 0x0f, 0xa4,
	0xdc, 0x4f, 0xb9, 0x6e, 0xfb, 0xc3, 0x95, 0x76, 0xca, 0xbd, 0x7a, 0xff, 0x5b, 0xa0, 0x5d, 0x49,
	0x37, 0x5a, 0x93, 0xec, 0x18, 0xd4, 0xb1, 0x10, 0x44, 0x66, 0xd9, 0x0c, 0xd8, 0x98, 0xae, 0x18,
	0x83, 0xb3, 0x7e, 0x0c, 0xf5, 0xf2, 0x18, 0xbc, 0xfb, 0x6a, 0xcb, 0x6a, 0xc3, 0xd6, 0x54, 0x91,
	0x6f, 0x6b, 0x6d, 0xd7, 0x6d, 0xfd, 0x0f, 0x40, 0x9f, 0x24, 0xf3, 0xf7, 0xea, 0xc7, 0xe7, 0x77,
	0xe0, 0x44, 0xf1, 0x13, 0xd3, 0xcc, 0xcd, 0xc1, 0xf9, 0x32, 0x4d, 0x25, 0xd8, 0xd7, 0xa1, 0x70,
	0x58, 0xbc, 0x29, 0xb3, 0xce, 0x2b, 0xb9, 0x4d, 0x1a, 0x1d, 0x92, 0x3f, 0x38, 0xef, 0x9b, 0xb5,
	0x9c, 0xfe, 0x36, 0x12, 0x52, 0x4d, 0x46, 0x32, 0x89, 0xe7, 0x3a, 0x7f, 0xcb, 0x37, 0x40, 0x59,
	0x13, 0x3c, 0x25, 0x26, 0x41, 0xcb, 0x37, 0x40, 0x89, 0xac, 0x0e, 0x7a, 0xba, 0x2d, 0x5f, 0x9f,
	0xd5, 0x0c, 0xe3, 0x94, 0x4e, 0x08, 0xcf, 0x46, 0x9b, 0xa1, 0x52, 0x8d, 0xf5, 0x9d, 0x6b, 0x54,
	0xb3, 0x98, 0x47, 0x42, 0x22, 0x57, 0x8f, 0x74, 0xdb, 0x2c, 0x54, 0xe8, 0xe0, 0xb3, 0x0b, 0x3a,
	0x85, 0xfd, 0x8e, 0xf0, 0xd7, 0x28, 0x20, 0x70, 0x0c, 0xdc, 0xab, 0x30, 0x1c, 0xc7, 0x04, 0xfe,
	0xb6, 0x9a, 0xb6, 0xf2, 0x3c, 0x4f, 0xbd, 0xf5, 0x75, 0x95, 0x33, 0x79, 0x7b, 0xf0, 0x06, 0xb8,
	0x23, 0x22, 0x15, 0xe1, 0x9a, 0x3e, 0x5e, 0x52, 0x22, 0xa4, 0x0a, 0xdc, 0x91, 0xec, 0x4f, 0x70,
	0xe0, 0x13, 0xca, 0x5e, 0xc9, 0x56, 0xbe, 0x93, 0xb5, 0x7c, 0x8b, 0x9a, 0xee, 0x08, 0xe6, 0xc1,
	0xec, 0x87, 0x6a, 0x52, 0x4b, 0xe0, 0xed, 0xc1, 0x07, 0x70, 0x34, 0x22, 0x52, 0x81, 0xeb, 0xf7,
	0xbf, 0xa2, 0xb9, 0x24, 0x1c, 0x9e, 0x7f, 0xc0, 0x6a, 0xdc, 0x3b, 0xf2, 0x8e, 0xc1, 0xe1, 0x88,
	0x48, 0x25, 0x73, 0x24, 0x64, 0x14, 0x6c, 0x23, 0xbd, 0xf8, 0x70, 0x4b, 0xf4, 0x75, 0xdd, 0x35,
	0xb8, 0xd7, 0x3f, 0xa6, 0xfa, 0x43, 0xd4, 0xdd, 0x24, 0xaf, 0x8a, 0xd8, 0x3c, 0xc2, 0x31, 0xe8,
	0xe4, 0x64, 0xc5, 0x17, 0xf3, 0x62, 0x23, 0xe5, 0x68, 0x33, 0xe1, 0x2d, 0x68, 0x67, 0x84, 0xdb,
	0xa6, 0x68, 0xc2, 0xb6, 0x29, 0x9c, 0xf5, 0xaa, 0xbf, 0x40, 0x1b, 0x7b, 0x55, 0x11, 0x1b, 0xc9,
	0xae, 0xcf, 0xff, 0x3d, 0x2b, 0xff, 0x27, 0xfa, 0x83, 0x51, 0xf6, 0x48, 0x45, 0xf2, 0x68, 0xe0,
	0xc4, 0xd5, 0xce, 0xe1, 0xf7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x76, 0xf9, 0x9c, 0x84, 0x67, 0x09,
	0x00, 0x00,
}
